// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: product.proto

package product

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Product service

type ProductService interface {
	Detail(ctx context.Context, in *DetailRequest, opts ...client.CallOption) (*Detailesponse, error)
}

type productService struct {
	c    client.Client
	name string
}

func NewProductService(name string, c client.Client) ProductService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "product"
	}
	return &productService{
		c:    c,
		name: name,
	}
}

func (c *productService) Detail(ctx context.Context, in *DetailRequest, opts ...client.CallOption) (*Detailesponse, error) {
	req := c.c.NewRequest(c.name, "Product.Detail", in)
	out := new(Detailesponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Product service

type ProductHandler interface {
	Detail(context.Context, *DetailRequest, *Detailesponse) error
}

func RegisterProductHandler(s server.Server, hdlr ProductHandler, opts ...server.HandlerOption) error {
	type product interface {
		Detail(ctx context.Context, in *DetailRequest, out *Detailesponse) error
	}
	type Product struct {
		product
	}
	h := &productHandler{hdlr}
	return s.Handle(s.NewHandler(&Product{h}, opts...))
}

type productHandler struct {
	ProductHandler
}

func (h *productHandler) Detail(ctx context.Context, in *DetailRequest, out *Detailesponse) error {
	return h.ProductHandler.Detail(ctx, in, out)
}
